# Generated by Django 6.0.5 on 2026-05-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
